name: Check Spelling

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Spelling
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: '{docs,static,src}/**/*.{md,mdx,js,ts,jsx,tsx,yml,yaml,json}'
